### ISSUE TITLE
Imported SGF has the first move numbered as zero

### ISSUE THREAD

**Issue by tussosedan** [rooklift/ogatak#108]
When importing an SGF (specifically I tried with ones exported from OGS), the first move shows up as number 0. 

On a new empty board, however, the empty board is move 0, and the first move is move 1.

Loving Ogatak so far, keep up the good work!

**Comment by rooklift** [comment]
Hmm can you post an example?

**Comment by rooklift** [comment]
So after a quick investigation I found this does happen on "Handicap 1" (i.e. no komi) games, because OGS treats the first Black stone as if it's a handicap stone...

If that's the circumstance, Ogatak is displaying it correctly, given what's in the SGF.

**Comment by tussosedan** [comment]
You're right, that's strange. I'll take it up with the OGS folks, closing the issue here.

**Comment by rooklift** [comment]
I made Ogatak handle this as a special case.
