### ISSUE TITLE
v1.9.3-Linux can not startup, GPU Goodbye

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#109]
OS: Debian 12
Terminal: Konsole 22.12.3
```
# after download, unzip and chmod +x ...
./ogatak 
[31073:1225/131619.063761:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

```

**Comment by rooklift** [comment]
Two suggestions:

* Find the Ogatak config file (if it exists), possibly somewhere like `$HOME/.config/Nibbler/config.json` and ensure `enable_hw_accel` is set to `false.
* If this isn't sufficient or possible, try running `./ogatax --no-sandbox`

Let me know if either of these steps work...

**Comment by HackYardo** [comment]
- The 1 step: already disable hw accel in `~/Downloads/ogatak-1.9.3-linux/resources/app/modules/config_io.js #106 "enable_hw_accel": false,`
- The 2 step: works fine
- BTW, can Ogatak only analyze kifu sgf files or AI self-play, but not AI-human play?

**Comment by rooklift** [comment]
Not sure what you're asking for - you can play against the AI from the Misc menu, for example.

**Comment by HackYardo** [comment]
But there are no "**PASS**" for human to end a game?  In most Go rulesets, *2 consecutive passes can end a game*.

**Comment by rooklift** [comment]
Well, you may certainly regard the game as finished at any time you like...
