### ISSUE TITLE
Ideographic Space for Chinese infoboxes

### ISSUE THREAD

**Issue by rooklift** [rooklift/ogatak#116]
Hello @CGLemon and @Bandysol 

As of 2.0.0, Ogatak can display both Traditional and Simplified Chinese in the infobox. Clearly the layout is kind of messed up, but the first thing I want to fix is this: when you mouseover a move, the word used switches:

* 最佳手 --> 本手

As a cheap hack to maintain the layout, I have gone ahead and added a U+3000 character (ideographic space) to 本手 (making it now "　本手" to maintain its width at 3 (so nothing changes in the layout as the text switches). Does that seem reasonable?

It fixes the issue on my machine at least, but I presumably don't have the same fonts as you both. As long as it displays properly for you I'm happy.

Now that I think about it, this could also fix some display issues I get in the SGF info screen...

Also - @CGLemon - the Simplified translation uses 黑 and 白 for colours in the infobox - can I do the same with yours? Is it the exact same characters?

**Comment by rooklift** [comment]
It's correct that the two things have different meaning (it switches from "best move" to "this move" meaning the move being hovered over).

As long as there's no issues with using the special space character my intention is to do so.

**Comment by rooklift** [comment]
i.e. when hovering over the 3,3 point here the word switches as described:

![image](https://github.com/rooklift/ogatak/assets/16438795/e63ecfa9-bef0-4fb2-ac63-a0a0fb9776cb)

Is that not correct?

**Comment by rooklift** [comment]
Thanks. @CGLemon - 本手 is also present in the Traditional translation (though it was unused until 2.0.0) - do you have a view on this?

**Comment by CGLemon** [comment]
* However, 该点位 or 本点位 is better.
Yes, It should be better. In the  traditional case, it is```本點位```. But I think we could use ```變化圖 ``` instead of them?

* the Simplified translation uses 黑 and 白 for colours in the infobox - can I do the same with yours? Is it the exact same characters?
Do you mean ```INFO_PANEL_B``` and ```INFO_PANEL_W```. It is OK if you want to fix them.

**Comment by rooklift** [comment]
> Do you mean INFO_PANEL_B and INFO_PANEL_W. It is OK if you want to fix them.

Yes. I will.

**Comment by rooklift** [comment]
I guess this matter is resolved. If anyone comes across any issues with any translation do let me know.
