### ISSUE TITLE
What does the "per-move ownership info from KataGo" option do ?

### ISSUE THREAD

**Issue by size-1** [rooklift/ogatak#118]
Hello, thank you for your work !

You're suggesting to disabling the "_per-move ownership info from KataGo_" option, for performance reasons. 
What is this option supposed to do in the first place?

**Comment by rooklift** [comment]
If you have enabled PV mouseover (in the Display menu) then it will change the displayed ownership when you move your mouse curser over a candidate move - this requires KataGo to send a lot of data, which can conceivably bog things down...

**Comment by size-1** [comment]
Ah thank you, it makes sense now !
