### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by nobrowser** [rooklift/ogatak#126]
Sorry, this probably looks like a really stupid question. But you see, I am not a JS person, or a Web person. I am just desperate to find a SGF editor I can use on a GNU/Linux system. So how do I actually start this application? Do I need a browser? Do I need to be online? What file to open?

Maybe there *is* a bug here: this could be mentioned in README.md ?

-- 
Ian

**Comment by rooklift** [comment]
Download the latest binary, currently https://github.com/rooklift/ogatak/releases/download/v2.0.7/ogatak-2.0.7-linux.zip

Unzip the file and run the file called ogatak therein.

This was packaged on Windows so may lack the proper file permissions. You may need to use chmod to set the binary to be executable. Something like `chmod 777 ogatak`

**Comment by rooklift** [comment]
Any luck?

**Comment by nobrowser** [comment]
Hi, I don't think I'll be trying that, sorry. Not to imply anything, but I'm from the Linux world and we don't just plop binaries into the system. Thanks for your help, though.

**Comment by rooklift** [comment]
In that case, acquire Electron and run `electron .` in the src directory.
