### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by ParmuzinAlexander** [rooklift/ogatak#22]
Alternative theme is here https://github.com/ParmuzinAlexander/go-themes/tree/master/ogatak/resources/app/gfx

**Comment by ParmuzinAlexander** [comment]
Alternative layout

**Comment by ParmuzinAlexander** [comment]
Alternative layout
https://imgur.com/idcI3QC
resources\app\ogatak.css
```
body {
	background-color: #080808ff;
	color: #efefefff;
	height: 100%;
	margin: 0;
	overflow: hidden;
	padding: 0;
	user-select: none;
	width: 100%;
}

::-webkit-scrollbar {
	pointer-events: auto;
	background-color: #181818ff;
}

::-webkit-scrollbar-thumb {
	pointer-events: auto;
	background-color: #444444ff;
}

#gridder {
	display: grid;
	height: 100vh;
	grid-template-columns: min-content min-content min-content 1fr;
	grid-template-rows: min-content min-content 1fr;
	grid-template-areas:
		"b c a a"
		"b c d e"
		"b c d f";
}

#tabdiv {
	/* background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQYV2Pg4OD4DwABTAEYzq6tsQAAAABJRU5ErkJggg=="); */
	grid-area: d;
	font-family: monospace, monospace;
	height: 100vh;
	margin: 0;
	padding: 0 0 0 0;
	overflow-x: hidden;
	overflow-y: auto;
	pointer-events: auto;
}

#comments {
	grid-area: f;
	font-family: 'Noto Mono', monospace;
	margin: 0 0 0 0;
	overflow-x: hidden;
	overflow-y: auto;
	white-space: pre-wrap;
}

#graphcanvas {
	display: block;				/* Stops the parent element from being 4px bigger... */
	grid-area: c;
	margin: 0;
	z-index: 1;
}

#graphpositioncanvas {
	display: block;				/* Stops the parent element from being 4px bigger... */
	grid-area: c;
	margin: 0;
	z-index: 2;
}

#treecanvas {
	display: block;
	grid-area: e;
	margin: 0 0 0 0;
}

#boardbg {
	background-image: url("./gfx/subdued_board.png");
	grid-area: b;
	margin: 0 0 0 0;
	z-index: 1;
}

#boardtable {
	grid-area: b;
	border-collapse: collapse;
	margin: 0 0 0 0;
	pointer-events: auto;
	z-index: 2;
}

#boardcanvas {
	grid-area: b;
	margin: 0 0 0 0;
	pointer-events: none;
	z-index: 3;
}

#boardinfo {
	grid-area: a;
	color: #e0b872ff;
	font-family: 'Noto Mono', monospace;
	line-height: 150%;
	white-space: pre;
	margin: 0 0 0 0;
}

.info_highlight {
	color: #ffffffff;
}

#preloaders {
	display: none;
	grid-area: b;
	z-index: 4;
}

td {
	background-color: transparent;
	background-size: contain;
	border: 0;
	margin: 0;
	padding: 0;
}
```

**Comment by rooklift** [comment]
Although it's probably a failure on my part, there are parts of the JS which assume a certain layout when calculating some sizes, so I don't immediately know whether this sort of rearrangement is safe to do.

Also, I see that, when 2 tabs are in play, the border around the active one isn't quite right.

**Comment by ParmuzinAlexander** [comment]
Everything works great, don't worry. 
Just using the same color for the border and the board is a strange idea.
I used #444444 for midline_graph_colour and border, in my opinion it looks better https://i.imgur.com/TJPfJGQ.png

**Comment by rooklift** [comment]
btw the draw code in some places assumes the average wood colour is a certain value (which it uses to cheaply "erase" small parts of the board), however as of v1.2.5 there is a file in /gfx which you can adjust.

**Comment by ParmuzinAlexander** [comment]
@rooklift Okay, I'll take a look later, unless something bad happens. I usually use #dcb771 for solid color. But after version 1.0.1 there is a problem with the new layout.
"b_g info info"
"b_g tabs t_c"
tabs and t_c cut from the bottom, because of this, large comments with scrolling are not displayed.

**Comment by rooklift** [comment]
Yeah some div ids got renamed at some point I think.

**Comment by rooklift** [comment]
(I mean to be clear, I'm not exactly encouraging you to do anything, I dunno if I'll ever write any code to support changing theme.)

**Comment by rooklift** [comment]
The requirement for `wood_colour.json` was removed in 1.5.4.

**Comment by rooklift** [comment]
And in 1.5.5 I'm going to change the filename to just `board.png`.
