### ISSUE TITLE
What's the core details of "Lizzie-ish"?

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#23]
*The issue should be asked in Lizzie repo, but it is not in developing by its author since last year.*
Half Go GUIs bulit on LeelZero or KataGo that can be found at Github are lizzie-ish. Lizzie-ish Go GUIs have their common features, e.g. real time analyzing(**ponder always on?**). But what's the core details of a lizzie-ish Go GUI?
For example, 
- Sabaki uses GTP, can load any GTP engine
- KaTrain uses KataGo's JSON, can only run KataGo.

Here, **GTP/KataGoJSON are the core details** that make KaTrain and Sabaki very different.

What's the core details of  "lizzie-ish"? When will you call a Go GUI lizzie-ish? What makes differences?
*I want to ask this issue because my devices  can not run a lizzie-ish Go GUI at a skin-friendly temperature.*

**Comment by rooklift** [comment]
It's not a term that's defined anywhere, but I was thinking of:

* Display of variations with mouse-over
* Display of multiple possible moves on the board, perhaps coloured by strength
* Display of statistics (e.g. win%) on the board
