### ISSUE TITLE
[Feature Request] Control analyze behavior by hand

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#40]
I have installed Ogatak on ubuntu.
Very glad to see the Ogatak becomes more and more powerful. But it seems that Ogatak can not add a vertex to analyze or limit search by vertex yet (not only analyze or don't analyze somewhere AI wants, but also somewhere player wants).

**Comment by rooklift** [comment]
I'm not sure how likely I am to support this sort of advanced feature - it's sort of a distant possibility at the moment.

**Comment by rooklift** [comment]
I've added this to my list of stuff that could conceivably be added, #15,  so closing here.
