### ISSUE TITLE
Wrong Ownership Color

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#42]
![image](https://user-images.githubusercontent.com/57677458/158008347-e6db0d59-9e7c-4a92-b042-2c9b298272c0.png)
In the picture, a white stone named `number 3` has black color ownership! Is it a mistake?

**Comment by rooklift** [comment]
Probably not. The ownership map is based on the whole subtree for the selected move, so can disagree somewhat with the PV.

Can you post the precise position that led to this?

**Comment by HackYardo** [comment]
I'm sorry I didn't save the position because it was played ramdomly.
I try to redo it, and finally get a similiar one again( the mode is the last 6block newtork):
![image](https://user-images.githubusercontent.com/57677458/158015985-314a36f1-1e3f-45cf-8fb7-b3510696a610.png)
![image](https://user-images.githubusercontent.com/57677458/158015994-9d216d44-6097-43f2-afb3-d5834c32c59a.png)

**Comment by rooklift** [comment]
I'm pretty confident that it's showing you what KataGo is really sending.

**Comment by HackYardo** [comment]
Oh, I see what you mean, the ownership is not after PV moves but before them. If play the game as the PV shows, the ownership will be fairly nicer:
![image](https://user-images.githubusercontent.com/57677458/158023088-a93f9a91-7c57-41b1-a246-3458552f4b38.png)

BTW, will Ogatak support `auto-update` in the future?

**Comment by rooklift** [comment]
It's not something I've looked into. (I'd expect development pace on Ogatak to reduce fairly soon though, I've done most of what I was hoping to do.)
