### ISSUE TITLE
No `batch analyze` in Ogatak?

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#47]
I hear it that the KataGo's `analyze` sub-command 
>  is designed to accept many different positions all at the same time and search them simultaneously.

While the `gtp` sub-command 
> is designed to have you declare a board size in advance and then play an entire game from there, searching only one position at a time. Therefore you can invest a slightly longer startup time in return for **improved performance** later.

So, if no `batch analyze`, **`gtp` is better than `analyze`**, right?

[Reference](https://github.com/lightvector/KataGo/issues/619#issuecomment-1073273120)

**Comment by rooklift** [comment]
Possibly? I don't know.

**Comment by rooklift** [comment]
If I'm understanding the discussion there, the benefit would only be for smaller board sizes?

**Comment by HackYardo** [comment]
> If I'm understanding the discussion there, the benefit would only be for smaller board sizes?

The analyze will be faster if batch several positions by analyze-sub-cmd, neither those positions belongs to a game nor multiple games.
But I find it that Ogatak analyze positions `one by one`?  So I open this issue.

**Comment by rooklift** [comment]
It's mostly done the way it is for simplicity.

**Comment by rooklift** [comment]
I just ran a test where I sent all the positions of a game at once, and compared it to the speed of how Ogatak works now, and it wasn't much different honestly. Less than 10% I think, which is not nothing, but not too huge either.

**Comment by HackYardo** [comment]
Oooh, I see.

**Comment by HackYardo** [comment]
Hey, I try KaTrain's analyze config [here](https://github.com/sanderland/katrain/blob/master/katrain/KataGo/analysis_config.cfg), and it accelerate Ogatak around 0.26!
Modify analyze config from default to Katrain:
```bash
# logDir = analysis_logs
 conservativePass = true
numAnalysisThreads = 12
#numSearchThreadsPerAnalysisThread = 16
numSearchThreads = 8
nnMaxBatchSize = 96
nnCacheSizePowerOfTwo = 20 
nnMutexPoolSizePowerOfTwo = 16
```
Speed Test:
```julia
KaTrainSpeed = 1
OgatakSpeed_DefaultAnalyzeConfig = 0.87
OgatakSpeed_KatrainAnalyzeConfig = 1.10
OgatakSpeed_GainRate = 1.1/0.87 -1 ≈ 0.26
```
You can try it, and maybe you could add some info about accelerate into **README**?

**Comment by rooklift** [comment]
I'm afraid the effect of various settings depends on hardware and such... this config didn't improve things for me. Still I guess I can add a note in the readme...
