### ISSUE TITLE
it not working!!!

### ISSUE THREAD

**Issue by bxc2739** [rooklift/ogatak#49]
![image](https://user-images.githubusercontent.com/101810221/168457799-26b3e6ea-4539-43fa-a8db-065fd3a1973a.png)

**Comment by rooklift** [comment]
Hmm. Can you:

* Confirm you have the latest version of KataGo.
* Open the `Dev` --> `Show engine stderr` item and see what it says.

**Comment by rooklift** [comment]
Ah, I see you're having the [same problem](https://github.com/sanderland/katrain/issues/533) in Katrain, which means it's some issue you're having with KataGo, not the GUI.

**Comment by rooklift** [comment]
I mean maybe I can help you get to the bottom of it, but I doubt it can be Ogatak's problem given that KaTrain isn't working either.
