### ISSUE TITLE
Any ideas about the SGF format of kifu analyze data? 

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#51]
The GNUGo, Pachi, SAI, LZ, KG, Sabaki, KaTrain, Lizzie, q5Go, LizGoban, Ogatak, etc are good at most cases, but the format of analyze data has no standard, every bot every gui has their format, extreme example: KaTrain save the analyze data but not load. If there is a standard, we could exchange not only the sgf's game tree and mark-up, but also the analyze data.
I find it that LizGoban has the same format of Lizzie and Ogatak has the same format of Sabaki, and Ogatak deal with many other format gib, ugi, etc. It looks like handling kifu formats' issues is a key feature of Ogatak. So, do you have any ideas about analyze data standardizing?

**Comment by rooklift** [comment]
Ogatak only saves winrate (as `SBKV` tags, like Sabaki uses) and score (as `OGSC`, which I arbitrarily chose since I don't think Sabaki does this) but I'm not keen to save the whole analysis as it would make the SGF files rather large.

**Comment by HackYardo** [comment]
- I just download a sgf file from OGS, there are C[Black's win rate: %15.4 visits: 507] but no OGSV[], something wrong?
- And the game has only 225 moves, but the OGS sgf file has 9000+ lines, it is too redundant 😱 
- I agree with you that sgf file should be lightweight, only score and winrate are everymove to plot curves, the others, e.g. ownship, final status, visit, playout, are in C[] somemove.

**Comment by rooklift** [comment]
`OGSC` is an Ogatak thing, I arbitrarily chose it, it stands for Ogatak Score.

**Comment by HackYardo** [comment]
Oh, fine, it looks like there are none left.
