### ISSUE TITLE
Please add explicit setup instructions

### ISSUE THREAD

**Issue by GustavBertram** [rooklift/ogatak#55]
I've downloaded KataGo and Okatak, but despite the reference to "taking a minute to set up", I have been unable to connect the board interface to the engine. I assume it's user error.

I've confirmed that the engine works at least, using qGo and a gtp configuration.

Please add explicit setup instructions.

**Comment by rooklift** [comment]
The process should be:

* Setup menu --> Locate KataGo [find the katago.exe]
* Setup menu --> Choose weights... [find the weights file]

**Comment by GustavBertram** [comment]
I meant, please add the instructions in the README.

I did actually follow those instructions, but it seems there's some other reason my engine is crashing.

**Comment by rooklift** [comment]
I've added something to the readme.

But for your specific problem, can you describe what happens?

**Comment by GustavBertram** [comment]
Huh. It had a CL_MEM_OBJECT_ALLOCATION_FAILURE before, but I'm not seeing it anymore.

Anyway, thanks for the README update, am closing this as resolved.
