### ISSUE TITLE
Multiple Language Support

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#56]
Would Ogatak add i18n feature in the long long future?

**Comment by rooklift** [comment]
It's conceivable. Menus are probably easy enough, then there's other stuff like alert messages and the GUI display itself (i.e. the text at the top) which would be a little more trouble.

**Comment by rooklift** [comment]
Still, I'm interested. I'll try and translate it into English first... meaning I'll create a file with all the needed English strings, which could then be modified for other languages.

**Comment by rooklift** [comment]
Is there a language in particular you want to help with? For the menus, I need the translations like so:

https://github.com/rooklift/ogatak/blob/main/src/modules/translate.js#L10-L137

i.e. leave the CAPITAL stuff alone, and just replace the strings on the right side.

**Comment by HackYardo** [comment]
Uh, Chinese is not hard for me, but for many languages' translation, I suggest to get help from **Disord**(leelazero and friends) and **OGS**.
And as you may know, I'm not a programmer and my repo's `sgf` and `gtp` is under long long developing for many months, actually, I plan to make them done in one year... In fact, I don't know what's the difference between L10N, T9N, I18N, G11N. So I have no enough time and won't take park in your repo, sorry for that!

**Comment by rooklift** [comment]
Well, if anyone wants to create a translation for any language, see the instructions at the top of:

https://github.com/rooklift/ogatak/blob/main/src/modules/translate.js

**Comment by rooklift** [comment]
I guess we're well under way with this now.
