### ISSUE TITLE
[Feature Request] Waiting for some milliseconds before displaying PV.

### ISSUE THREAD

**Issue by CGLemon** [rooklift/ogatak#63]
It was annoying to me that ogatak show PV suddenly when I analyzed some games. It should be lag some time. For example, Sabaki. As a go player, I think that it is high prior feature.

**Comment by rooklift** [comment]
A good suggestion. I'd need to think carefully about how to do this, it's not so easy.

**Comment by rooklift** [comment]
So I think I can wait before displaying it. I think I'm still not going to *animate* it move by move, which would likely be a lot of work.

**Comment by rooklift** [comment]
Oh, how would you translate "Delay before drawing PV" ? :)

**Comment by CGLemon** [comment]
Wow you have already done it! Very fast!

I may translate "Delay before drawing PV" to "主變化懸停延遲".

Waiting for your next release.

**Comment by rooklift** [comment]
I hope it's what you were looking for.
