### ISSUE TITLE
Is possible to distinctive mark the main line from others forks?

### ISSUE THREAD

**Issue by CGLemon** [rooklift/ogatak#68]
Here is it. I guess the main line and fork line are same color. May we make a difference from each other?

![Screenshot from 2022-08-12 17-34-48](https://user-images.githubusercontent.com/39462842/184328124-3f14d568-4d47-43ba-b0e2-b4fc78217e1c.png)

**Comment by rooklift** [comment]
Do you mean the circles on the board marking the next move?

**Comment by CGLemon** [comment]
Yes.

**Comment by rooklift** [comment]
I'll add it to the [list of ideas](https://github.com/rooklift/ogatak/issues/15).
