### ISSUE TITLE
add a Timer

### ISSUE THREAD

**Issue by HackYardo** [rooklift/ogatak#69]
Would Ogatak add a timer like KaTrain or q5Go in the long long future?

**Comment by rooklift** [comment]
What sort of timer?

**Comment by HackYardo** [comment]
Have you ever participated in an offline Go tournament? After each move, you need to tap the clock to stop the timing. It's just a clock for timing...

**Comment by CGLemon** [comment]
I guess there is no time manager in the Kata Go analysis interface after reading the document. It is a little wired for ogatak to add time manager because the CUI focus on the analysis, not game playing (?).

**Comment by HackYardo** [comment]
- It's not there doesn't mean it can't be. KaTrain is also based on the KataGo analyze protocol but with a clock.

- There are several kinds of GUIs for board games, for playing, editing, publishing, analyzing, database, and so on. I think that **among them, playing is a must, because playing means generating games**, otherwise you have to open games generated by other friendly GUIs, but this is not customary, at least for me, I don't play with KaTrain and then edit with Sabaki, one GUI per day. And then, **clocking is a basic requirement for playing**, just look at the many chess GUIs, it is not hard to find out...

- As far as I know, the author of Ogatak is also the second author of Sabaki. And I think one of the major shortcomings of Sabaki is the lack of a clock, I wonder what Ogatak will do?

**Comment by rooklift** [comment]
I don't think I'll add this. Trying to keep things simple (it's already too complicated). Still, I'll add it to the [suggestions list](https://github.com/rooklift/ogatak/issues/15).
