### ISSUE TITLE
own_alt in board_drawer is not used by ownership alt options

### ISSUE THREAD

**Issue by rinick** [rooklift/ogatak#92]
when I select ownership->whole board in the menu, it uses "own_alt" type for board_drawer
when I select ownership->whole board (alt), "own_alt" is not used

this is really confusing

**Comment by rooklift** [comment]
Ah I think that's because at some point in the past I switched which style would be the main style and which would be the alt.

**Comment by rooklift** [comment]
#Fixed in #[bb31788](https://github.com/rooklift/ogatak/commit/bb31788cdd74bdf81286eb6f1d1d5e6b4372be1c)
