### ISSUE TITLE
[bug report]Misc-Engine plays black/white auto-unchecked while backward the game

### ISSUE THREAD

**Issue by jojobm** [rooklift/ogatak#97]
As the say, when I check the [Misc->Engine plays black] option. It works as expected when I go  forward the game.
But the engine stops analysis after I take some steps back.

**Comment by rooklift** [comment]
That's intended really. Any navigation other than playing moves for your colour will end that mode.

**Comment by jojobm** [comment]
> 
I expect to have a quick shortcut to activate AI to play as black (analysis + candidate moves), which would be helpful to utilize researching local responses while also prompting myself to think about the best response for white, similar to a guided mode . Is that possible?

**Comment by rooklift** [comment]
If you just mean turning on the analysis, you can press space bar.

If you mean to actually play the move, perhaps I'll add something for the engine taking whichever colour is currently to play...

**Comment by jojobm** [comment]
> If you just mean turning on the analysis, you can press space bar.
> 
> If you mean to actually play the move, perhaps I'll add something for the engine taking whichever colour is currently to play...

Yes，I mean actually play against AI with  AI only showing the candidates and I  choice / rechoice

**Comment by jojobm** [comment]
> If you just mean turning on the analysis, you can press space bar.
> 
> If you mean to actually play the move, perhaps I'll add something for the engine taking whichever colour is currently to play...

Yes，I mean actually play against AI with AI only showing the candidates and I choice / rechoice. But turn off the candidate colour  display of mine( analysis on or off is not  important)

**Comment by jojobm** [comment]
> If you just mean turning on the analysis, you can press space bar.
> 
> If you mean to actually play the move, perhaps I'll add something for the engine taking whichever colour is currently to play...

Yes，I mean actually play against AI with AI only showing the candidates and I choice / rechoice. But turn off the candidate colour display of mine( analysis on or off is not important).
Currently ,in fact ,I have to press space bar after every move now to get it.

**Comment by rooklift** [comment]
I'm not sure I'm fully understanding.

**Comment by jojobm** [comment]
> I'm not sure I'm fully understanding.

Sorry for the confusion. After reviewing the code, I realized that my description was indeed easy to be misunderstood.In fact, the feature I need is closer to a pure analysis mode, and it only analyzes the selected side. For example, when analyzing the black side, display the candidates when it's black's turn. I will manually choose the best or my preferred move. Then, when it's white's turn, do not display any candidates and stop analyzing. I will think and make my choice. When it is black's turn again, I can roughly gauge how good the previous move was based on the winning rate. If it's particularly bad, I will go back and rethink. At the same time, I will repeatedly study how white's thought process changes in response to different moves by black.The reason I raised this issue in the gameplay mode is that I set a longer number of visits, and the gameplay mode happened to simulate the one-sided analysis. However, the gameplay mode becomes invalid after going back, which is why I had this question.

**Comment by rooklift** [comment]
It's a bit niche so I don't expect to add it as a feature. You may be able to get what you want with a code adjustment in `hub.js`...

```javascript```
if (this.__autoanalysis || this.__backanalysis || this.__autoplay /* || this.__play_colour */) {  // Line 422
```

Then in console, do `config.autoanalysis_visits = 1000000` or something (to prevent it from actually playing moves when it's its turn.)

Note that if you ever manually toggle pondering via spacebar it will still turn off the mode.

**Comment by jojobm** [comment]
Thans，that's works fine.
